set_property PACKAGE_PIN V22 [get_ports Qs(0)]
set_property PACKAGE_PIN W22 [get_ports Qs(1)]
set_property PACKAGE_PIN U19 [get_ports Qs(2)]
set_property PACKAGE_PIN U14 [get_ports Qs(3)]
set_property PACKAGE_PIN U22 [get_ports ys]
set_property PACKAGE_PIN G22 [get_ports en]
set_property PACKAGE_PIN F22 [get_ports rst]


set_property IOSTANDARD LVCMOS33 [get_ports Qs(0)]
set_property IOSTANDARD LVCMOS33 [get_ports Qs(1)]
set_property IOSTANDARD LVCMOS33 [get_ports Qs(2)]
set_property IOSTANDARD LVCMOS33 [get_ports Qs(3)]
set_property IOSTANDARD LVCMOS33 [get_ports ys]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports rst]


set_property PACKAGE_PIN V22 [get_ports {Qs[3]}]
set_property PACKAGE_PIN W22 [get_ports {Qs[2]}]
set_property PACKAGE_PIN U19 [get_ports {Qs[1]}]
set_property PACKAGE_PIN U14 [get_ports {Qs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Qs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
